### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by davakula** [uvejota/homeassistant-edata#136]
Hola,

disculpad, pero no he conseguido hacer funcionar la integración, y dado que llevo más de un mes dándole vueltas, imagino que no puede ser un problema de Datadis, sino de algo que esté haciendo yo mal.

Pego aquí el log:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

2022-12-06 20:46:41.027 INFO (SyncWorker_3) [edata.helpers] Update requested for CUPS xxxx from 2021-12-01T00:00:00 to 2022-12-05T23:59:00
2022-12-06 20:46:41.028 INFO (SyncWorker_3) [edata.helpers] Identified missing consumptions: 2021-12-01T00:00:00 - 2022-12-05T23:59:00
2022-12-06 20:46:41.029 INFO (SyncWorker_3) [edata.helpers] Identified missing maximeter: 2021-12-01T00:00:00 - 2022-10-06T23:00:00, 2022-10-09T15:30:00 - 2022-12-05T23:59:00
2022-12-06 20:46:41.030 INFO (SyncWorker_3) [edata.connectors.datadis] GET https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXXXXXXXXXXX&distributorCode=2&startDate=2022/09&endDate=2022/11&measurementType=0&pointType=5&
2022-12-06 20:46:42.556 INFO (SyncWorker_3) [edata.connectors.datadis] GET https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXXXXXXXXXX&distributorCode=2&startDate=2022/09&endDate=2022/11&measurementType=0&pointType=5&
2022-12-06 20:46:44.320 ERROR (SyncWorker_3) [edata.connectors.datadis] 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2022-12-06T20:46:44.288+0100"} at https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXXXXXXXXXX&distributorCode=2&startDate=2022/09&endDate=2022/11&measurementType=0&pointType=5&
2022-12-06 20:46:44.432 WARNING (MainThread) [custom_components.edata.statistics] Some stats are missing for XXXX
2022-12-06 20:46:44.448 WARNING (MainThread) [custom_components.edata.coordinator] Some data is missing, will try to fetch later

Gracias y un saludo,

**Comment by paloke** [comment]
Buenas,

Estoy igual al intentar añadir la integración me aparece el error: No se pudo cargar el flujo de configuración: 500 Internal Server Error Server got itself in trouble

¿Alguna sugerencia?

Saludos.

**Comment by uvejota** [comment]
Ambos casos parecen ser errores diferentes:

> Hola,
> 
> disculpad, pero no he conseguido hacer funcionar la integración, y dado que llevo más de un mes dándole vueltas, imagino que no puede ser un problema de Datadis, sino de algo que esté haciendo yo mal.
> 
> Pego aquí el log:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received messages, upgraded, tail = self._request_parser.feed_data(data) File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
> 
> 2022-12-06 20:46:41.027 INFO (SyncWorker_3) [edata.helpers] Update requested for CUPS xxxx from 2021-12-01T00:00:00 to 2022-12-05T23:59:00 2022-12-06 20:46:41.028 INFO (SyncWorker_3) [edata.helpers] Identified missing consumptions: 2021-12-01T00:00:00 - 2022-12-05T23:59:00 2022-12-06 20:46:41.029 INFO (SyncWorker_3) [edata.helpers] Identified missing maximeter: 2021-12-01T00:00:00 - 2022-10-06T23:00:00, 2022-10-09T15:30:00 - 2022-12-05T23:59:00 2022-12-06 20:46:41.030 INFO (SyncWorker_3) [edata.connectors.datadis] GET https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXXXXXXXXXXX&distributorCode=2&startDate=2022/09&endDate=2022/11&measurementType=0&pointType=5& 2022-12-06 20:46:42.556 INFO (SyncWorker_3) [edata.connectors.datadis] GET https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXXXXXXXXXX&distributorCode=2&startDate=2022/09&endDate=2022/11&measurementType=0&pointType=5& 2022-12-06 20:46:44.320 ERROR (SyncWorker_3) [edata.connectors.datadis] 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2022-12-06T20:46:44.288+0100"} at https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXXXXXXXXXX&distributorCode=2&startDate=2022/09&endDate=2022/11&measurementType=0&pointType=5& 2022-12-06 20:46:44.432 WARNING (MainThread) [custom_components.edata.statistics] Some stats are missing for XXXX 2022-12-06 20:46:44.448 WARNING (MainThread) [custom_components.edata.coordinator] Some data is missing, will try to fetch later
> 
> Gracias y un saludo,

Esto pinta a indisponibilidad del servidor en ese momento, dejándolo suficiente tiempo (ojo, puede necesitar días, datadis a veces tiene rachas malas) debería autorecuperarse.



> Buenas,
> 
> Estoy igual al intentar añadir la integración me aparece el error: No se pudo cargar el flujo de configuración: 500 Internal Server Error Server got itself in trouble
> 
> ¿Alguna sugerencia?
> 
> Saludos.

En este caso, el error es similar pero en el setup de la integración (se comprueban las credenciales antes de crear la integración). Inténtalo más tarde / en otro momento y debería funcionar.
