### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by ar5627** [uvejota/homeassistant-edata#163]
Componente de HACS ok
Al intentar añadir la integración e-data desde "Dispositivos y Servicios, Integraciones" da error con el mensaje "Unknown error occurred" justo al intentar validar las credenciales y CUPS. Puedo acceder correctamente a Datadis con mi usuario/contraseña. No he tenido problemas al configurar otras integraciones.
Muchas gracias.
Datos del registro:

_```
Este error se originó a partir de una integración personalizada.

Logger: aiohttp.server
Source: custom_components/edata/config_flow.py:57
Integration: Integración edata (documentation, issues)
First occurred: 10:33:16 (1 occurrences)
Last logged: 10:33:16

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='datadis.es', port=443): Max retries exceeded with url: /nikola-auth/tokens/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/edata/config_flow.py", line 82, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/home/homeassistant/.homeassistant/custom_components/edata/config_flow.py", line 57, in validate_input
    result = await hass.async_add_executor_job(api.login)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.10/site-packages/edata/connectors/datadis.py", line 137, in login
    return self._get_token()
  File "/srv/homeassistant/lib/python3.10/site-packages/edata/connectors/datadis.py", line 117, in _get_token
    response = self._session.post(
  File "/srv/homeassistant/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/srv/homeassistant/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='datadis.es', port=443): Max retries exceeded with url: /nikola-auth/tokens/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
```_

**Comment by jbustdel** [comment]
Otro más con el mismo error. Ha ocurrido desde que actualice a 2023.3.4. Desde ese momento da error el sensor creado. He eliminado la integración, reinstalada y ya no me deja acceder con mi usuario y contraseña. En datadis está ok.

**Comment by jbustdel** [comment]
Todo funciona ahora en mi caso, de nuevo.

**Comment by ar5627** [comment]
Cierto, ya funciona. Gracias
