### ISSUE TITLE
Solución: edata en estado unavailable

### ISSUE THREAD

**Issue by simblagon** [uvejota/homeassistant-edata#170]
Hola,

  Tengo un problema con el sensor.edata se queda en estado unavailable, he probado a eliminar el sensor, desinstalar incluso el paquete edata y el error persiste.

¿Os ha pasado? ¿Podeis ayudarme?

![image](https://user-images.githubusercontent.com/129552763/233010269-5b7969ab-e86b-481f-8eb2-292850154ded.png)

Muestra este error cuando intenta borrar las estadísticas:

error fetching edata_983ex data: Detected unsafe call not in recorder thread
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/edata/coordinator.py", line 127, in _async_update_data
    await self.statistics.clear_all_statistics()
  File "/config/custom_components/edata/statistics.py", line 162, in clear_all_statistics
    await get_db_instance(self.hass).async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 674, in clear_statistics
    instance.statistics_meta_manager.delete(session, statistic_ids)
  File "/usr/src/homeassistant/homeassistant/components/recorder/table_managers/statistics_meta.py", line 324, in delete
    self._assert_in_recorder_thread()
  File "/usr/src/homeassistant/homeassistant/components/recorder/table_managers/statistics_meta.py", line 125, in _assert_in_recorder_thread
    raise RuntimeError("Detected unsafe call not in recorder thread")
RuntimeError: Detected unsafe call not in recorder thread

**Comment by simblagon** [comment]
Solved. Instalé el complemento SQLite Web y en la tabla statistics_meta he buscado por los valores del source edata y después los he borrado:

Buscar (Ir a pestaña Query de la tabla statistics_meta):
select * from statistics_meta where source="edata"

Borrar (Ir a pestaña Query de la tabla statistics_meta):
delete from statistics_meta where id=191;  —> Uno a uno
delete from statistics_meta where source="edata"; Todos las estadísticas de source edata

![image](https://user-images.githubusercontent.com/129552763/233149659-e565b36c-508e-4edc-af40-81beba2dbdaa.png)


Saludos

**Comment by drufoval** [comment]
Hola,
Yo tengo el mismo problema... He tratado de reconfigurar la integración y la carga inicial funciona, pero después deja de cargar los días sucesivos...
Mi versión de home assistant es: 2023.5.3

un saludo.
