### ISSUE TITLE
Incompatibilidad HA 2023.6

### ISSUE THREAD

**Issue by tomassanjuan** [uvejota/homeassistant-edata#177]
Version HA: Home Assistant 2023.6.0b1

La última versión de Home Assistant rompe la integración. Han creado distintos nuevos tipos de fechas, horas y creo que es la parte que está fallando. También han hecho bump a Python 3.11

Adjunto log. Gracias!

```
2023-06-01 13:29:42.787 ERROR (SyncWorker_5) [edata.helpers] Unhandled exception while updating attributes
2023-06-01 13:29:42.788 ERROR (SyncWorker_5) [edata.helpers] datetime64 type does not support sum operations
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/edata/helpers.py", line 373, in process_data
process_method()
File "/usr/local/lib/python3.11/site-packages/edata/helpers.py", line 554, in process_cost
proc = BillingProcessor(
^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/edata/processors/base.py", line 18, in __init__
self.do_process()
File "/usr/local/lib/python3.11/site-packages/edata/processors/billing.py", line 152, in do_process
_t = _t.groupby([_t.datetime.dt.to_period(opt["period"])]).sum()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 2263, in sum
result = self._agg_general(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1422, in _agg_general
result = self._cython_agg_general(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1507, in _cython_agg_general
new_mgr = data.grouped_reduce(array_func)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 1506, in grouped_reduce
applied = blk.apply(func)
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/internals/blocks.py", line 329, in apply
result = func(self.values, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1490, in array_func
result = self.grouper._cython_operation(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 959, in _cython_operation
return cy_op.cython_operation(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 645, in cython_operation
self._disallow_invalid_ops(dtype, is_numeric)
File "/usr/local/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 257, in _disallow_invalid_ops
raise TypeError(f"datetime64 type does not support {how} operations")
TypeError: datetime64 type does not support sum operations
```

**Comment by uvejota** [comment]
La librería Pandas ha actualizado a la 2.0 y hay algunos cambios importantes. Lo solucionaré lo antes posible bloqueando la versión a la última <2.0

Gracias por el aviso

**Comment by JokeRsevilla** [comment]
Hola! hay alguna forma de hacerlo funcionar mientras sale la nueva versión?

Gracias por el trabajo!

**Comment by uvejota** [comment]
He subido un hotfix (versión 2023.06.1).

Creo que está corregido.

Un saludo,

**Comment by tomassanjuan** [comment]
Buenas, testeando la última versión, no soluciona el error. Crashea al iniciar la integración. Genera un output en el log de casi 2500 líneas. En caso de ser necesario, lo subo. Gracias!

```
2023-06-11 13:40:40.426 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package e-data==1.1.2: error: subprocess-exited-with-error
× Building wheel for pandas (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [2277 lines of output]

2275 omitted lines!

error: command 'gcc' failed: No such file or directory
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
2023-06-11 13:43:02.127 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration edata: Requirements for edata not found: ['e-data==1.1.2'].
```

**Comment by uvejota** [comment]
Um.

Me parece raro ya que yo lo he instalado sin problema en HA 2023.06.X

Parece tener problemas para ‘instalar’ la librería pandas.

Tendré que echarle un ojillo

El 11 jun 2023, a las 19:53, Tom ***@***.***> escribió:

﻿

Buenas, testeando la última versión, no soluciona el error. Crashea al iniciar la integración. Genera un output en el log de casi 2500 líneas. En caso de ser necesario, lo subo. Gracias!

2023-06-11 13:40:40.426 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package e-data==1.1.2: error: subprocess-exited-with-error
× Building wheel for pandas (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [2277 lines of output]

2275 omitted lines!

error: command 'gcc' failed: No such file or directory
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
2023-06-11 13:43:02.127 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration edata: Requirements for edata not found: ['e-data==1.1.2'].

**Comment by alexsalvo1** [comment]
Me pasa lo mismo a mi...

**Comment by cbolumar** [comment]
El mismo error con la nueva versión.

Un saludo y muchas gracias por esta magnifica integración.

**Comment by Ie0nard0** [comment]
A mi también me aparece el mismo error. Un saludo

**Comment by uvejota** [comment]
Pues confirmado, no funciona en 2023.6

Le tengo que echar un ojillo

El 12 jun 2023, a las 8:05, Ie0nard0 ***@***.***> escribió:

﻿

A mi también me aparece el mismo error. Un saludo
