### ISSUE TITLE
Detected blocking call to open with args ('/tmp/edata_recent_queries.json',) inside the event loop by custom integration 'edata' at custom_components/edata/config_flow.py, line 59

### ISSUE THREAD

**Issue by Josep-Softcatala** [uvejota/homeassistant-edata#244]
2024-08-09 06:44:16.874 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/tmp/edata_recent_queries.json',) inside the event loop by custom integration 'edata' at custom_components/edata/config_flow.py, line 59: api = DatadisConnector(data[CONF_USERNAME], data[CONF_PASSWORD]) (offender: /usr/local/lib/python3.12/site-packages/edata/connectors/datadis.py, line 110: with open(self._recent_queries_file, encoding="utf8") as dst_file:), please create a bug report at https://github.com/uvejota/homeassistant-edata/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 456, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/edata/config_flow.py", line 132, in async_step_user
    info = await validate_step_user(self.hass, user_input)
  File "/config/custom_components/edata/config_flow.py", line 59, in validate_step_user
    api = DatadisConnector(data[CONF_USERNAME], data[CONF_PASSWORD])

2024-08-09 06:44:27.682 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform edata is taking over 10 seconds.
2024-08-09 06:45:17.976 ERROR (MainThread) [homeassistant.components.sensor] Setup of platform edata is taking longer than 60 seconds. Startup will proceed without waiting any longer.

**Comment by yuuues** [comment]
Version of HA?
If its 2024.8.0, you need to use the alpha version

https://github.com/uvejota/homeassistant-edata/issues/243

**Comment by josmellop** [comment]
Yo tengo el mismo problema, y estoy usando la alpha-9

![IMG_20240809_161006](https://github.com/user-attachments/assets/0dd9c368-0ec2-44d5-b798-b3851902dd92)

**Comment by Josep-Softcatala** [comment]
> Version of HA? If its 2024.8.0, you need to use the alpha version
> 
> #243

Yes, It's HA 2024.8.0
And yes, an alpha version (2024.07.0-alpha.9) has solved the problem.
Now, I don't know if I can trust 2024.07.0-beta...
Thanks!
