### ISSUE TITLE
ValueError: Config entry was never loaded!

### ISSUE THREAD

**Issue by mabusdogma** [uvejota/homeassistant-edata#245]
Registrador: homeassistant.config_entries
Fuente: config_entries.py:819
Ocurrió por primera vez: 10:11:18 a. m. (2 ocurrencias)
Último inicio de sesión: 10:11:21 a. m.

Error unloading entry AL0F for sensor
Error unloading entry LW0F for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 819, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 136, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by oliveraf** [comment]
La solucion: https://github.com/uvejota/homeassistant-edata/issues/243#issuecomment-2276560935
