### ISSUE TITLE
Error de pyton actualizando datos de datadis

### ISSUE THREAD

**Issue by ornosa** [uvejota/homeassistant-edata#29]
Hola, a ver si me podeis echar una mano. Llevo dos días probando todo tipo de configuraciones y no soy capaz de recibir datos de Datadis.

Tengo esta configuración en el fichero de configuration.yaml
#Configuracion de edata
sensor:
  - platform: edata
    username: NUMERODNI
    password: CONTRASEÑA
    cups: CUPSCOPIADODEDATADIS1
   - platform: edata
    username: NUMERODNI
    password: CONTRASEÑA
    cups: CUPSCOPIADODEDATADIS2

No he incluido PROVIDER: DATADIS porque no me queda claro si hay que meterlo. En la configuración de la documentación por lo menos no lo indica, aunque he visto algún sitio que habla de esto. En algún momento también probé poniendo el proveedor en el archivo de configuración y nada...

Los sensores se muestran en pero están en estado loading desde hace un par de horas y no tiene ningún atributo. 
![image](https://user-images.githubusercontent.com/92144439/136714400-64f70f59-1929-46ed-b90c-8cf93f328a82.png)

Las graficas de apexchart no se muestran y sale este error:

![image](https://user-images.githubusercontent.com/92144439/136714437-409f51dd-41c7-4bbb-b9a5-4f8f9db7ef6f.png)

En el registro de errores se muestran estos:

Logger: edata.helpers
Source: /usr/local/lib/python3.9/site-packages/edata/helpers.py:121
First occurred: 21:29:21 (4 occurrences)
Last logged: 22:58:56

unhandled exception while updating data for CUPS CF1X
unhandled exception while updating data for CUPS GX1X

2021-10-10 22:58:56 ERROR (SyncWorker_1) [edata.helpers] unhandled exception while updating data for CUPS CF1X
2021-10-10 22:58:56 ERROR (SyncWorker_1) [edata.helpers] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/edata/helpers.py", line 117, in update_data
updated = self._datadis.update (cups, date_from, date_to)
File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 166, in update
self._update_maximeter (cups, dcode, start, end)
File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 213, in _update_maximeter
r = self.get_max_power (cups, distributorCode, startDate, endDate) if (datetime.today().date() != self._last_update['maximeter'].date()) or (len (self._data['maximeter']) == 0) else []
File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 311, in get_max_power
r = self._send_cmd("https://datadis.es/api-private/api/get-max-power", data=data)
File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 109, in _send_cmd
if (r.status_code == 200 and r.json()):
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

¿Alguna idea de lo que puedo estar haciendo mal?

Instalación actual de 32 bits de HA pero previamente también me fallaba la de 64.
Instalado HACS según las instrucciones y configurado el repositorio de EDATA y configurada la integración.
Las entidades se muestran en estado loading.
![image](https://user-images.githubusercontent.com/92144439/136714071-d1d15eb1-09c0-4469-9f49-a37ec4c84526.png)

Gracias de antemano.

**Comment by ornosa** [comment]
5 dias ya loading...y todavia sin datos ni atributos

Siguen saliendo errores:

Logger: edata.helpers
Source: /usr/local/lib/python3.9/site-packages/edata/helpers.py:121
First occurred: 12 de octubre de 2021 20:45:11 (70 occurrences)
Last logged: 08:01:15

unhandled exception while updating data for CUPS GX1X
unhandled exception while updating data for CUPS CF1X

Logger: edata.helpers
Source: /usr/local/lib/python3.9/site-packages/edata/helpers.py:122
First occurred: 12 de octubre de 2021 20:45:11 (70 occurrences)
Last logged: 08:01:15

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/edata/helpers.py", line 117, in update_data
    updated = self._datadis.update (cups, date_from, date_to)
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 166, in update
    self._update_maximeter (cups, dcode, start, end)
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 213, in _update_maximeter
    r = self.get_max_power (cups, distributorCode, startDate, endDate) if (datetime.today().date() != self._last_update['maximeter'].date()) or (len (self._data['maximeter']) == 0) else []
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 311, in get_max_power
    r = self._send_cmd("https://datadis.es/api-private/api/get-max-power", data=data)
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 109, in _send_cmd
    if (r.status_code == 200 and r.json()):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:628
First occurred: 12 de octubre de 2021 20:44:59 (11 occurrences)
Last logged: 01:01:22

Update of sensor.edata_cf1x is taking over 10 seconds
Update of sensor.edata_gx1x is taking over 10 seconds

Toda ayuda es bienvenida.
