### ISSUE TITLE
Error al cargar sensor y graficas

### ISSUE THREAD

**Issue by Frowxen** [uvejota/homeassistant-edata#95]
Desde ayer sin ningún cambio de configuración ha comenzado a fallar el sensor y por ende las graficas.
Ha estado funcionando correctamente semanas desde que lo instalé y ahora no carga.
Habrá habido algún cambio en DATADIS

Pego el Log

> Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/edata/sensor.py:5
Integration: Integración edata (documentation, issues)
First occurred: 16:27:02 (1 occurrences)
Last logged: 16:27:02

Error setting up entry 17AY for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 204, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 147, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 309, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/edata/sensor.py", line 5, in <module>
    from edata.helpers import EdataHelper
  File "/usr/local/lib/python3.9/site-packages/edata/helpers.py", line 8, in <module>
    from edata.connectors import DatadisConnector
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 11, in <module>
    from edata.processors import DataUtils as du
  File "/usr/local/lib/python3.9/site-packages/edata/processors.py", line 7, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/usr/local/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.9/site-packages/numpy/core/overrides.py", line 9, in <module>
    from numpy.compat._inspect import getargspec
  File "/usr/local/lib/python3.9/site-packages/numpy/compat/__init__.py", line 12, in <module>
    from . import py3k
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 978, in get_code
  File "<frozen importlib._bootstrap_external>", line 647, in _compile_bytecode
ValueError: bad marshal data (unknown type code)

**Comment by uvejota** [comment]
Um... ¿Sigues teniendo este problema?

Parece un error al instalar una subdependencia de pandas/numpy (py3k)
